project:
  type: website
  render:
    - "*.qmd"
    - "!exercises/exercises.Rmd"
    - "!slides/[0-9]*.qmd"
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600

execute:
  freeze: auto

website:
  page-navigation: true
  title: "Parameterized Reporting with Quarto: R-Ladies DC"
  description: "Homepage for the 2024 R-Ladies DC Parameterized Reports with Quarto Workshop"
  site-url: "https://jadeyryan.quarto.pub/rladies-dc-quarto-params/"
  favicon: "images/jr-logo-circle.webp"

  repo-url: https://github.com/jadeynryan/rladies-parameterized-quarto
  repo-actions: [source, edit, issue]

  page-footer:
    left: "&copy; 2024 Jadey Ryan"
    center: "Website built with ❤︎️ and [Quarto](https://quarto.org/)."
    right: "Inspired by [R/Medicine 2023 workshop](https://github.com/shannonpileggi/rmedicine-data-cleaning-2023), inspired by [R/Medicine 2022 Workshop](https://github.com/ddsjoberg/clinical-reporting-gtsummary-rmed), inspired by [@minebocek](https://twitter.com/minebocek)."
    background: "#07483f"

  sidebar:
    background: "#07483f"
    logo: "images/jr-logo-quarto.webp"
    logo-alt: "Two hex stickers side by side with a heart joining them in the middle. Left sticker is Jadey's cat logo. Right sticker is the Quarto logo."
    pinned: true
    align: center
    style: docked
    type: dark
    tools:
      - icon: github
        href: https://github.com/jadeynryan/rladies-parameterized-quarto
        text: GitHub
    contents:
     - href: index.qmd
       text: Home
     - href: prework.qmd
       text: Pre-work
     - href: materials.qmd
       text: Materials
     - href: license.qmd
       text: License

format:
  html:
    theme: [flatly, theme.scss]
    toc: true
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    code-copy: true
    code-overflow: scroll
    mainfont: Atkinson Hyperlegible
    highlight-style: a11y

# lightbox extension
# https://github.com/quarto-ext/lightbox
filters:
  - lightbox
lightbox:
  desc-position: right  # position of description
  # match: auto # give all images lightbox treatment
  effect: zoom # how lightbox opens/closes
  loop: false # doesn't loop to first image in gallery
