# Child documents {.section}

## Generate dynamic contents with a "child" template

-   `knitr::knit_child()` and `knitr::knit_expand()` are functions from R Markdown that also work with Quarto

-   "child" document is a template, which is run with different parameters

-   "main" document includes the output from all the different iterations of the child document

## Do not run interactively!

Code chunks including [`knitr::knit_child()`](https://rdrr.io/pkg/knitr/man/knit_child.html) are not supposed to be used interactively (see this [Stack Overflow response](https://stackoverflow.com/a/16847729) from the `knitr` developer Yihui
Xie). If run interactively, you will get an error similar to the one shown
below.

``` {.r}
Error in `purrr::map_chr()`:
ℹ In index: 1.
Caused by error in `setwd()`:
! character argument expected
```

Read a description of this issue in WSDA's {soils} R package [vignette](https://wa-department-of-agriculture.github.io/soils/articles/troubleshoot.html#error-when-run-interactively).

## Learn more about child documents

-   Qiushi Yan's blog post [*Generating dynamic contents in R Markdown and
    Quarto*](https://www.qiushiyan.dev/posts/dynamic-rmd-quarto/)
    
-   Yihui Xie's *R Markdown Cookbook* sections on [`knitr::knit_child()`](https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html#child-document) and [`knitr::knit_expand()`](https://bookdown.org/yihui/rmarkdown-cookbook/knit-expand.html)

-   Isabella Velásquez's [*Getting started with report writing using Quarto* at
    26:00](https://youtu.be/Sf__ERCSgIA?si=Z4DLAHdqgRvof0FB&t=1560).

# 💃🏻 Demo {.demo}

Main document: `6-demo-knit-child.qmd`

Child document: `_child-template.qmd`
